### ISSUE TITLE
Node-Red Nodes

### ISSUE THREAD

**Issue by usauerbrey** [trollsoft7/waterkotte-resuemat-nodered#2]
Could please add, which Node-Red Node packets must be installed to use your flow
Thanks Uwe

**Comment by trollsoft7** [comment]
Following palette needs to be installed:
node-red-contrib-home-assistant-websocket
node-red-contrib-buffer-parser
node-red-node-serialport

Does this help?

**Comment by usauerbrey** [comment]
Thanks, yes this helps, maybe you should add it to the readme

**Comment by trollsoft7** [comment]
Did already. Hope you can get it running!

**Comment by HubertCom** [comment]
Ich glaube du hadt den falschen Code veröffentlicht.  

Im flow.json beim durchschauen sind Namen, Fernseher ....  vorhanden.

**Comment by trollsoft7** [comment]
Danke - oops - richtiger Code wieder vorhanden.

**Comment by wodixx** [comment]
nur zur Ergänzung,bei mir fehlte auch noch:
node-red-show-value

**Comment by trollsoft7** [comment]
danke - hab ich auch noch hinzugefügt.
